name: Revy
on: [pull_request, pull_request_target]

jobs:
  reviewpad-action:
    name: Reviewpad action
    runs-on: ubuntu-latest
    steps:
      - name: Runs reviewpad action
        uses: reviewpad/action@v0.0.1
