name: Revy
on:
  - pull_request

jobs:
  reviewpad-action:
    name: Reviewpad action
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Runs reviewpad action
        uses: reviewpad/action@canary

